---
- name: Setup RKE2 (master node)
  hosts: servers
  become: true
  roles:
    #- rke2_master
    - argocd
  tags:
    - master

- name: Setup RKE2 (agent nodes)
  hosts: agents
  become: true
  roles:
    - rke2_agent
  tags:
    - agent
