---
- name: Initialize nodes
  hosts: all
  roles:
    - init
  tags:
    - init

- name: Setup RKE2 (master node)
  hosts: servers
  roles:
    - rke2_master
    - argocd
  tags:
    - master

- name: Setup RKE2 (agent nodes)
  hosts: agents
  roles:
    - rke2_agent
  tags:
    - agent
