- name: Install dependencies
  ansible.builtin.dnf:
    name:
      - tar
      - unzip
    state: present

- name: Create system user node_exporter
  ansible.builtin.user:
    name: node_exporter
    shell: /sbin/nologin
    system: true
    create_home: false

- name: Download node exporter archive
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.9.0/node_exporter-1.9.0.linux-amd64.tar.gz"
    dest: /opt/node_exporter-1.9.0.linux-amd64.tar.gz

- name: Extract node exporter archive
  ansible.builtin.unarchive:
    src: /opt/node_exporter-1.9.0.linux-amd64.tar.gz
    dest: /opt
    remote_src: true
    creates: /opt/node_exporter

- name: Create symbolic link to node_exporter
  ansible.builtin.file:
    src: /opt/node_exporter-1.9.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    state: link

- name: Create systemd service definition
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify:
    - Reload systemd
    - Restart Node Exporter

- name: Ensure node exporter service is started and enabled
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true
